// Weapon definitions. Levels reference enemy weapons by key, so new levels can
// mix and match these or add new entries here.

export const PLAYER_WEAPON = {
  name: 'PA-9 Pulse Rifle',
  model: 'player_rifle',
  magazine: 32,
  reserve: 192,
  interval: 0.085, // seconds between shots (~700 rpm)
  damage: 34,
  headMultiplier: 2.4,
  spreadHip: 0.016,
  spreadAim: 0.004,
  spreadMove: 0.02,
  reloadTime: 1.8,
  range: 300,
  recoil: 0.012,
  tracer: [0.45, 0.95, 1.0],
  sound: 'pulse',
};

// Enemy weapons. `burst` fires N shots `burstInterval` apart, then waits `interval`.
export const ENEMY_WEAPONS = {
  shotgun: {
    name: 'Breaching Shotgun',
    model: 'gun_shotgun',
    pellets: 8,
    damage: 6,
    spread: 0.075,
    interval: 1.05,
    burst: 1,
    burstInterval: 0,
    magazine: 6,
    reloadTime: 2.6,
    range: 32,
    preferredRange: [3, 9],
    aimError: 0.05,
    reaction: 0.45,
    tracer: [1.0, 0.75, 0.35],
    sound: 'shotgun',
  },
  bullpup: {
    name: 'Bullpup Rifle',
    model: 'gun_bullpup',
    pellets: 1,
    damage: 9,
    spread: 0.012,
    interval: 1.2,
    burst: 3,
    burstInterval: 0.085,
    magazine: 30,
    reloadTime: 2.2,
    range: 110,
    preferredRange: [10, 60],
    aimError: 0.045,
    reaction: 0.7,
    tracer: [1.0, 0.85, 0.45],
    sound: 'bullpup',
  },
  carbine: {
    name: 'Assault Carbine',
    model: 'gun_carbine',
    pellets: 1,
    damage: 6,
    spread: 0.035,
    interval: 0.9,
    burst: 7,
    burstInterval: 0.095,
    magazine: 30,
    reloadTime: 2.0,
    range: 80,
    preferredRange: [8, 30],
    aimError: 0.055,
    reaction: 0.55,
    tracer: [1.0, 0.8, 0.4],
    sound: 'carbine',
  },
  dmr: {
    name: 'Marksman Rifle',
    model: 'gun_dmr',
    pellets: 1,
    damage: 30,
    spread: 0.002,
    interval: 2.6,
    burst: 1,
    burstInterval: 0,
    magazine: 10,
    reloadTime: 3.0,
    range: 220,
    preferredRange: [25, 200],
    aimError: 0.02,
    reaction: 1.0,
    laser: 1.1, // seconds of visible laser telegraph before each shot
    tracer: [1.0, 0.95, 0.7],
    sound: 'dmr',
  },
};
